---
# ironicbadger.docker-compose-generator
host_timezone: "US/Eastern"
docker_compose_hostname: "c137"

appdata_path: /mnt/nvmeu2/appdata
download_path: /mnt/downloads
storage_path: /mnt/rust
wd_domain_me: "wd.{{ domain_me }}"
m_wd_domain_me: "m.{{ wd_domain_me }}"

docker_compose_generator_uid: "1001"
docker_compose_generator_gid: "1001"

disabled_compose_files: []

# ironicbadger.packages
packages_perform_cleanup: True
package_list:
  - bcache-tools
  - btrfs-progs
  - curl
  - git
  - htop
  - intel-gpu-tools
  - proxmox-kernel-6.14
  - samba
  - samba-common-bin
  - smbclient
  - sudo
  - tmux
  - wget
  - which

# ironicbadger.nix-home-manager
nix_packages:
    # Unstable packages
    - nixpkgs-unstable.beszel

    # Stable packages
    - btop
    - coreutils
    - cifs-utils
    - drill
    - du-dust
    - dua
    - duf
    - entr
    - fastfetch
    - fd
    - fdupes
    - ffmpeg
    - figurine
    - go
    - iperf3
    - ipmitool
    - just
    - mc
    - mergerfs
    - ncdu
    - neofetch
    - nfs-utils
    - nmap
    - ripgrep
    - smartmontools
    - tree
    - unzip
    - watch
    - wget
    - wireguard-tools
    - zoxide

# nix-manager configuration
nix_user: "root"
nix_group: "root"
nix_home: "/root"
install_home_manager: true
git_username: "Alex Kretzschmar"
git_email: "{{ vault_cloudflare_account_email }}"

# ironicbadger.mounts
automount_drives: true
drive_mounts:
  # mergings
  - mountpoint: "/mnt/jbod"
    device: "/mnt/disks/disk*"
    fstype: "mergerfs"
    options:
      - "defaults"
      - "minfreespace=250G"
      - "allow_other"
      - "use_ino"
      - "cache.files=partial"
      - "dropcacheonclose=true"
      - "fsname=mergerfs-jbod"
  # data disks
  - mountpoint: "/mnt/disks/disk1"
    device: "/dev/disk/by-id/ata-WDC_WD180EDGZ-11B9PA0_3ZGA70DZ-part1"
    fstype: "btrfs"
    options:
      - "subvol=data"
      - "compress=zstd"
      - "defaults"
  - mountpoint: "/mnt/disks/disk2"
    device: "/dev/disk/by-id/ata-WDC_WD180EDGZ-11B9PA0_2TGGDS5Z-part1"
    fstype: "btrfs"
    options:
      - "subvol=data"
      - "compress=zstd"
      - "defaults"
  - mountpoint: "/mnt/disks/disk3"
    device: "/dev/disk/by-id/ata-WDC_WD180EDGZ-11B9PA0_2GH0M6HS-part1"
    fstype: "btrfs"
    options:
      - "subvol=data"
      - "compress=zstd"
      - "defaults"