---
# ironicbadger.docker-compose-generator
host_timezone: "US/Eastern"
docker_compose_hostname: "igloo"
docker_compose_generator_uid: "0"
docker_compose_generator_gid: "0"
disabled_compose_files: []

appdata_path: /mnt/nvmeu2/appdata
storage_path: /mnt/rust
igloo_domain_me: "igloo.{{ domain_me }}"

# ironicbadger.packages
packages_perform_cleanup: True
package_list:
  - curl
  - git
  - htop
  - intel-gpu-tools
  - samba
  - samba-common-bin
  - smbclient
  - sudo
  - tmux
  - wget
  - which

# zrepl configuration - using new unified job structure
zrepl_jobs:
  # Sink for c137 push jobs
  - name: "c137_sink"
    type: sink
    root_fs: "z2tank/backups/c137"
    serve:
      type: "tcp"
      listen: "100.91.74.29:27808"
      clients:
        "100.107.197.66": "data"  # Maps c137's IP to "data" to avoid duplication
    recv:
      placeholder:
        encryption: "off"
        
  # Sink for snowball push jobs
  - name: "snowball_sink"
    type: sink
    root_fs: "z2tank/backups/snowball"
    serve:
      type: "tcp"
      listen: "100.91.74.29:27809"  # Different port for snowball
      clients:
        "100.88.250.125": "data"  # Consistent naming pattern
    recv:
      placeholder:
        encryption: "off"
