---
# ironicbadger.caddy
caddy_tls_providers:
  - provider: cloudflare
    challenge_type: dns
    provider_api_token: "{{ cloudflare_token_caddy }}"
    resolver_ip: 1.1.1.1
caddy_endpoints:
  - friendly_name: wildcard for *.core.ktz.me
    fqdn: '*.core.ktz.me'
    tls_provider: cloudflare
    wildcard_endpoints:
      - friendly_name: smokeping
        fqdn: smokeping.core.ktz.me
        upstream: http://localhost:8007
  - friendly_name: wildcard for *.maple.ktz.me
    fqdn: '*.maple.ktz.me'
    tls_provider: cloudflare
    wildcard_endpoints:
      - friendly_name: px-moose
        fqdn: px.maple.ktz.me
        upstream: https://192.168.13.10:8006
        tls_insecure: true