---

# ironicbadger.figurine
figurine_name: neo-yeet

# local-neo-yeet
primary_user:
  name: alex
  shell: /bin/bash
  groups: sudo
  uid: 1000
  gid: 1000
samba_mounts:
  - mount_point: /mnt/appdata
    share: //10.42.1.42/nvme_appdata_appdata
    username: "{{ primary_user.name}}"
    password: "{{ vault_samba_alex_password }}"
    uid: "{{ primary_user.uid }}"
    gid: "{{ primary_user.gid }}"
