---

# ironicbadger.docker-compose-generator
host_timezone: "US/Eastern"
docker_compose_hostname: "morphnix"

appdata_path: /mnt/nvme-appdata
download_path: /mnt/downloads
storage_path: /mnt/jbod
bigrust_path: /mnt/bigrust
wd_domain_me: "wd.{{ domain_me }}"
m_wd_domain_me: "m.{{ wd_domain_me }}"

docker_compose_generator_uid: "1000"
docker_compose_generator_gid: "100"

disabled_compose_files: []

# ironicbadger.packages
packages_perform_cleanup: True
package_list:
  - curl
  - git
  - htop
  - smbclient
  - sudo
  - tmux
  - wget
  - which

# ironicbadger.nix-home-manager
nix_packages:
    # Unstable packages
    - nixpkgs-unstable.beszel

    # Stable packages
    - btop
    - coreutils
    - cifs-utils
    - drill
    - du-dust
    - dua
    - duf
    - entr
    - fastfetch
    - fd
    - ffmpeg
    - figurine
    - go
    - iperf3
    - ipmitool
    - just
    - mc
    - ncdu
    - neofetch
    - nfs-utils
    - nmap
    - ripgrep
    - smartmontools
    - tree
    - unzip
    - watch
    - wget
    - wireguard-tools
    - zoxide

# ironicbadger.mounts
automount_drives: true
drive_mounts:
  - mountpoint: "/mnt/parity/parity1"
    device: "/dev/disk/by-id/ata-WDC_WD180EDGZ-11B9PA0_3ZGA70DZ-part1"
    fstype: "ext4"
    opts: "defaults"

# nix-manager configuration
nix_user: "root"
nix_group: "root"
nix_home: "/root"
install_home_manager: true
git_username: "Alex Kretzschmar"
git_email: "{{ vault_cloudflare_account_email }}"
