---

docker_compose_generator_output_path: "/root"
containers:
  - service_name: netboot
    active: true
    image: lscr.io/linuxserver/netbootxyz
    ports:
      - 3000:3000
      - 69:69/udp
      - 3001:80
    include_global_env_vars: true
    restart: unless-stopped