services:
## media servers
  # plex
  # jellyfin
  # both require qsv so are on the host natively
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - "{{ appdata_path }}/mediaservers/audiobookshelf:/config"
      - "/mnt/rust/media/audiobooks:/audiobooks"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.wd.ktz.me`)"
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: "{{ docker_compose_generator_uid }}:{{ docker_compose_generator_gid }}"
    volumes:
      - "{{ appdata_path }}/mediaservers/navidrome:/data"
      - "/mnt/rust/media/music/library:/music:ro"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.navidrome.rule=Host(`navidrome.{{ m_wd_domain_me }}`)"
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
    environment:
      - ND_MUSICFOLDER=/music
      - ND_DEVFASTACCESSCOVERART=true
      - ND_COVERARTPRIORITY=embedded
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  cwa:
    image: crocodilestick/calibre-web-automated:latest
    container_name: cwa
    labels:
      - traefik.enable=true
      - "traefik.http.routers.cwa.rule=Host(`cwa.{{ m_wd_domain_me }}`)"
      - traefik.http.routers.cwa.entrypoints=websecure
      - traefik.http.routers.cwa.tls=true
      - traefik.http.services.cwa.loadbalancer.server.port=8083
      - traefik.http.middlewares.cwa-headers.headers.customRequestHeaders.X-Scheme=https
      - traefik.http.middlewares.cwa-headers.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.cwa-headers.headers.customRequestHeaders.X-Forwarded-Port=443
      - traefik.http.routers.cwa.middlewares=cwa-headers
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
      # Hardcover API Key required for Hardcover as a Metadata Provider, get one here: https://docs.hardcover.app/api/getting-started/
      - "HARDCOVER_TOKEN={{ cwa_hardcover_api_token }}"
      - NETWORK_SHARE_MODE=false
    volumes:
      - "{{ appdata_path }}/mediaservers/calibre-web/config:/config"
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - "{{ download_path }}/complete/books:/cwa-book-ingest"
      #- "{{ appdata_path }}/mediaservers/calibre-web/book-ingest:/cwa-book-ingest"
      - "{{ storage_path }}/media/books:/calibre-library"
      - "{{ appdata_path }}/mediaservers/calibre-web/calibre-plugins:/config/.config/calibre/plugins"
    restart: unless-stopped