services:
  # dashboard
  glance:
    image: glanceapp/glance
    container_name: glance
    volumes:
      - "{{ appdata_path }}/apps/glance/config:/app/config"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "core-glance"
      tsdproxy.container_port: 8080
    ports:
      - 8006:8080
    restart: unless-stopped
  # monitoring
  smokeping:
    image: lscr.io/linuxserver/smokeping:2.8.2-r3-ls130
    container_name: smokeping
    volumes:
      - "{{ appdata_path }}/apps/smokeping/config:/config"
      - "{{ appdata_path }}/apps/smokeping/data:/data"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "core-smokeping"
      tsdproxy.container_port: 80
    ports:
      - 8007:80
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    hostname: core
    restart: unless-stopped
  gotify:
    image: gotify/server:latest
    container_name: gotify
    volumes:
      - "{{ appdata_path }}/apps/gotify/data:/app/data"
    labels:
      - "tsdproxy.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`gotify.{{ apps_domain_me }}`)"
    ports:
      - 8010:80
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
      - "GOTIFY_DEFAULTUSER_PASS={{ gotify_default_pass }}"
    restart: unless-stopped
  igotify:
    image: ghcr.io/androidseb25/igotify-notification-assist
    container_name: igotify
    volumes:
      - "{{ appdata_path }}/apps/igotify/config:/app/data"
    labels:
      - "tsdproxy.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.igotify.rule=Host(`igotify.{{ apps_domain_me }}`)"
      - traefik.http.services.igotify.loadbalancer.server.port=8080
    ports:
      - 8011:8080
    environment:
      - "TZ={{ host_timezone }}"
      - "GOTIFY_URLS=http://gotify"
      - "GOTIFY_CLIENT_TOKENS={{ gotify_client_token }}"
    restart: unless-stopped
  librespeed:
    image: lscr.io/linuxserver/librespeed:5.4.1-ls231
    container_name: librespeed
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "core-librespeed"
      tsdproxy.container_port: 80
    ports:
      - 8008:80
    environment:
      - MODE=standalone
    restart: unless-stopped
  # collators
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    volumes:
      - "{{ appdata_path }}/apps/freshrss/data:/var/www/FreshRSS/data"
      - "{{ appdata_path }}/apps/freshrss/extensions:/var/www/FreshRSS/extensions"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.rule=Host(`rss.{{ apps_domain_me }}`)"
    environment:
      - TZ={{ host_timezone }}
      - CRON_MIN=13,43
      - "BASE_URL=https://rss.{{ apps_domain_me }}"
    restart: unless-stopped
