services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:5.4.20240804
    container_name: librespeed
    ports:
      - 8008:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MODE=standalone
      - TELEMETRY=true
      - "PASSWORD={{ testpass }}"
    restart: unless-stopped
