services:
## media servers
  jellyfin:
    image: jellyfin/jellyfin:12
    container_name: jellyfin
    hostname: jellyfin
    # Preserve the running host's scheduling priority.
    cpu_shares: 262144
    blkio_config:
      weight: 1000
    oom_score_adj: -1000
    cap_add:
      - SYS_NICE
    ulimits:
      nice: -20
      rtprio: 99
    entrypoint: ["/usr/bin/nice", "-n", "-20", "/jellyfin/jellyfin"]
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "{{ appdata_path }}/mediaservers/jellyfin:/config"
      - "{{ storage_path }}/media:{{ storage_path }}/media:ro"
      - /mnt/downloads:/downloads:ro
    labels:
      - traefik.enable=true
      - "traefik.http.routers.jellyfin.rule=Host(`jf.wd.ktz.me`)"
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    ports:
      - 2285:8096
      - 8096:8096
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ=US/Eastern"
      - "JELLYFIN_PublishedServerUrl=https://jf.wd.ktz.me"
    restart: unless-stopped
