services:
  # other apps
  ktz-pastebin:
    image: mkaczanowski/pastebin
    container_name: ktz-pastebin
    volumes:
      - "{{ appdata_path }}/ktz-pastebin:/var/lib/pastebin"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.ktzpaste.rule=Host(`paste.{{ domain_cloud }}`)"
      - traefik.http.routers.ktzpaste.entrypoints=websecure
      - traefik.http.routers.ktzpaste.tls.certresolver=cloudflare
      - traefik.http.services.ktzpaste.loadbalancer.server.port=8000
    command:
      - --address
      - 0.0.0.0
      - --db
      - /var/lib/pastebin/
      - --uri
      - https://paste.{{ domain_cloud }}
    restart: unless-stopped
  ktz-lychee:
    image: lycheeorg/lychee:v6.4.1
    container_name: ktz-lychee
    volumes:
      - "{{ appdata_path }}/ktz-lychee/app/config:/conf"
      - "{{ appdata_path }}/ktz-lychee/app/uploads:/uploads"
      - "{{ appdata_path }}/ktz-lychee/app/sym:/sym"
      - "{{ appdata_path }}/ktz-lychee/app/logs:/logs"
      - "{{ appdata_path }}/ktz-lychee/app/tmp:/lychee-tmp"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ktzlychee.rule=Host(`gallery.ktz.cloud`)
      - traefik.http.routers.ktzlychee.tls.certresolver=cloudflare
    environment:
      - "PHP_TZ={{ host_timezone }}"
      - "APP_URL=https://gallery.ktz.cloud"
      - DB_CONNECTION=mysql
      - DB_HOST=ktz-lychee-db
      - DB_PORT=3306
      - "DB_USERNAME={{ lychee_mysql_user }}"
      - "DB_DATABASE={{ lychee_mysql_database }}"
      - "DB_PASSWORD={{ lychee_mysql_password }}"
    depends_on:
      - ktz-lychee-db
    restart: unless-stopped
  ktz-lychee-db:
    image: mariadb:10.8.2-focal
    container_name: ktz-lychee-db
    volumes:
      - "{{ appdata_path }}/ktz-lychee/db:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD={{ lychee_mysql_root_password }}"
      - "MYSQL_PASSWORD={{ lychee_mysql_password }}"
      - "MYSQL_DATABASE={{ lychee_mysql_database }}"
      - "MYSQL_USER={{ lychee_mysql_user }}"
    restart: unless-stopped
  ktz-pocketid:
    image: ghcr.io/pocket-id/pocket-id
    container_name: pocketid
    environment:
      - "PUBLIC_APP_URL=https://id.{{ domain_me }}"
      - TRUST_PROXY=true
      - "MAXMIND_LICENSE_KEY={{ pocket_id_maxmind_key }}"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.pocketid.rule=Host(`id.{{ domain_me }}`)"
      - traefik.http.routers.pocketid.tls.certresolver=cloudflare
    volumes:
      - "{{ appdata_path }}/pocket-id/data:/app/backend/data"
    # Optional healthcheck
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: unless-stopped
  ktz-n8n:
    image: n8nio/n8n:latest
    container_name: ktz-n8n
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/ktz-n8n:/home/node/.n8n"
    environment:
      - N8N_HOST=n8n.{{ domain_cloud }}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_ENCRYPTION_KEY={{ n8n_encryption_key }}
      - NODE_ENV=production
      - "TZ={{ host_timezone }}"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.ktzn8n.rule=Host(`n8n.{{ domain_cloud }}`)"
      - traefik.http.routers.ktzn8n.entrypoints=websecure
      - traefik.http.routers.ktzn8n.tls.certresolver=cloudflare
      - traefik.http.services.ktzn8n.loadbalancer.server.port=5678
  ###
  ktz-hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:latest
    container_name: ktz-hedgedoc
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/ktz-hedgedoc/uploads:/hedgedoc/public/uploads"
    environment:
      - CMD_DB_URL=postgres://hedgedoc:{{ hedgedoc_db_password }}@ktz-hedgedoc-db:5432/hedgedoc
      - CMD_DOMAIN=md.{{ domain_cloud }}
      - CMD_URL_ADDPORT=false
      - CMD_PROTOCOL_USESSL=true
      - CMD_ALLOW_EMAIL_REGISTER=false
      - "CMD_TZ={{ host_timezone }}"
      - CMD_OAUTH2_PROVIDERNAME=PocketID
      - "CMD_OAUTH2_CLIENT_ID={{ hedgedoc_oauth_client_id }}"
      - "CMD_OAUTH2_CLIENT_SECRET={{ hedgedoc_oauth_secret }}"
      - CMD_OAUTH2_SCOPE=openid email profile
      - CMD_OAUTH2_TOKEN_AUTH_METHOD=client_secret_post
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=preferred_username
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_USER_PROFILE_URL=https://id.{{ domain_me }}/api/oidc/userinfo
      - CMD_OAUTH2_TOKEN_URL=https://id.{{ domain_me }}/api/oidc/token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://id.{{ domain_me }}/authorize
    depends_on:
      - ktz-hedgedoc-db
    labels:
      - traefik.enable=true
      - "traefik.http.routers.ktzhedgedoc.rule=Host(`md.{{ domain_cloud }}`)"
      - traefik.http.routers.ktzhedgedoc.entrypoints=websecure
      - traefik.http.routers.ktzhedgedoc.tls.certresolver=cloudflare
      - traefik.http.services.ktzhedgedoc.loadbalancer.server.port=3000
  ktz-hedgedoc-db:
    image: postgres:14-alpine
    container_name: ktz-hedgedoc-db
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/ktz-hedgedoc/database:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=hedgedoc
      - "POSTGRES_PASSWORD={{ hedgedoc_db_password }}"
      - POSTGRES_DB=hedgedoc

