roles:
#- src: ironicbadger.docker_compose_generator
#- src: ironicbadger.bash_aliases
#- src: ironicbadger.figurine

# submodules
  # - src: git+https://github.com/ironicbadger/ansible-role-caddy.git
  #   version: main

collections: []