roles:
#- src: ironicbadger.bash_aliases
#- src: ironicbadger.figurine

collections: []


## submodules
### Most 3rd party roles that are written by me should be imported as
### submodules to make testing easier when modifying those roles.
### There is a helper function in the justfile to make this easier.