---

- name: ensure target dir exists
  file:
    dest: "{{ appdata_path }}/short/authelia/"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  become: true

- name: template authelia config
  template:
    src: templates/users.yml.j2
    dest: "{{ appdata_path }}/short/authelia/users_database.yml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  become: true

- name: template authelia rules
  template:
    src: templates/configuration.yml.j2
    dest: "{{ appdata_path }}/short/authelia/configuration.yml"
    owner: "root"
    group: "root"
  become: true