---

- name: download latest release
  get_url:
    url: "{{ caddy_amd64_linux_cloudflare_binary_url }}"
    dest: /usr/local/bin/caddy
    owner: root
    group: root
    mode: a+x
  ignore_errors: true

- name: add the caddy group
  ansible.builtin.group:
    name: caddy

- name: Add the caddy user
  ansible.builtin.user:
    name: caddy
    group: caddy