services:
  manyfold:
    image: ghcr.io/manyfold3d/manyfold:latest
    container_name: manyfold
    volumes:
      - /mnt/appdata/apps/manyfold/libraries:/libraries
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DATABASE_ADAPTER=postgresql
      - DATABASE_HOST=manyfold-db
      - DATABASE_NAME=manyfold
      - DATABASE_USER=manyfold
      - DATABASE_PASSWORD=example1
      - SECRET_KEY_BASE=example1
      - REDIS_URL=redis://manyfold-redis:6379/1
    depends_on:
      - manyfold-db
      - manyfold-redis
    restart: unless-stopped
  manyfold-db:
    image: postgres:15
    container_name: manyfold-db
    volumes:
      - /mnt/appdata/apps/manyfold/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=manyfold
      - POSTGRES_PASSWORD=example1
    restart: unless-stopped
  manyfold-redis:
    image: redis:7
    container_name: manyfold-redis
    restart: unless-stopped