services:
  # immich-ml
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    container_name: immich-machine-learning
    volumes:
      - "/opt/apps/immich/cache:/cache"
    ports:
      - 3003:3003
    dns:
      - 1.1.1.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped