---

- name: Add the user
  ansible.builtin.user:
    name: "{{ primary_user.name }}"
    uid: "{{ primary_user.uid }}"
    groups: "{{ primary_user.groups }}"
    shell: "{{ primary_user.shell }}"
    append: true