services:
  # monitoring
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    volumes:
      - "{{ appdata_path }}/databases/smokeping/config:/config"
      - "{{ appdata_path }}/databases/smokeping/data:/data"
    labels:
      - traefik.enable=true
      - traefik.http.routers.smokeping.rule=Host(`smokeping.{{ dt_domain_me }}`)
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    hostname: deep-thought
    restart: unless-stopped
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    ports:
      - 8008:80
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
      - MODE=standalone
      - TELEMETRY=true
    restart: unless-stopped