services:
  ts-hoarder:
    image: tailscale/tailscale:latest
    container_name: hoarder-ts
    hostname: hoarder
    environment:
      - "TS_AUTHKEY={{ tailscale_authkey_cp }}"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/serve/hoarder.json
    volumes:
      - /root/appdata/hoarder/tailscale/state:/var/lib/tailscale
      - /root/appdata/hoarder/tailscale/serve:/serve
    ports:
      - 3030:3000
    dns: 1.1.1.1
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:0.24.1
    container_name: hoarder-web
    network_mode: service:ts-hoarder
    depends_on:
      - ts-hoarder
    volumes:
      - "{{ appdata_path }}/hoarder/data:/data"
    environment:
      - MEILI_ADDR=http://hoarder-meilisearch:7700
      - "MEILI_MASTER_KEY={{ hoarder_nextauth_masterkey }}"
      - BROWSER_WEB_URL=http://hoarder-chrome:9222
      - NEXTAUTH_URL=http://localhost:3030
      - "NEXTAUTH_SECRET={{ hoarder_nextauth_secret }}"
      - DATA_DIR=/data
      - "OPENAI_API_KEY={{ hoarder_openai_key }}"
      # - "OLLAMA_BASE_URL=http://10.42.1.12:11434"
      - "INFERENCE_TEXT_MODEL=gpt-4o-mini"
      - "INFERENCE_IMAGE_MODEL=gpt-4o-mini"
      ## archival-settings
      - CRAWLER_FULL_PAGE_SCREENSHOT=true
      - CRAWLER_FULL_PAGE_ARCHIVE=true
      - CRAWLER_JOB_TIMEOUT_SEC=120
      - CRAWLER_VIDEO_DOWNLOAD=true
      - MAX_ASSET_SIZE_MB=100
      - SERVER_VERSION=nightly
    restart: unless-stopped
  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    container_name: hoarder-chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped
  hoarder-meilisearch:
    image: getmeili/meilisearch:v1.12.2
    container_name: hoarder-meilisearch
    volumes:
      - "{{ appdata_path }}/hoarder/meilisearch:/meili_data"
    environment:
      - "MEILI_NO_ANALYTICS=true"
      - NEXTAUTH_URL=http://hoarder-web:3030
      - "NEXTAUTH_SECRET={{ hoarder_nextauth_secret }}"
      - MEILI_ADDR=http://127.0.0.1:7700
      - "MEILI_MASTER_KEY={{ hoarder_nextauth_masterkey }}"
      - MAX_ASSET_SIZE_MB=100
    restart: unless-stopped