services:
## media servers
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "{{ appdata_path }}/mediaservers/plex/config:/config"
      - "{{ storage_path }}:/data:ro"
      - /mnt/downloads:/downloads:ro
      - /mnt/bigrust:/mnt/bigrust:ro
      # ram transcode
      - /dev/shm:/transcode
    labels:
      - traefik.enable=false
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "{{ appdata_path }}/mediaservers/jellyfin:/config"
      - "{{ storage_path }}:/data:ro"
      - /mnt/downloads:/downloads:ro
      # ram transcode
      - /dev/shm:/transcode
    labels:
      - traefik.enable=true
      - "traefik.http.routers.jellyfin.rule=Host(`jf.{{ wd_domain_me }}`)"
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    ports:
      - 2285:8096
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
      - "JELLYFIN_PublishedServerUrl=jf.{{ wd_domain_me }}"
    hostname: us-rdu
    restart: unless-stopped
  # abs:
  #   image: advplyr/audiobookshelf
  #   container_name: abs
  #   volumes:
  #     - "{{ appdata_path }}/mediaservers/audiobookshelf/metadata:/metadata"
  #     - "{{ appdata_path }}/mediaservers/audiobookshelf/config:/config"
  #   labels:
  #     - traefik.enable=true
  #     - "traefik.http.routers.audiobookshelf.rule=Host(`abs.{{ wd_domain_me }}`)"
  #   ports:
  #     - 2284:80
  #   restart: unless-stopped
  ersatztv:
    image: jasongdove/ersatztv:latest-vaapi
    container_name: ersatztv
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "{{ appdata_path }}/mediaservers/ersatztv:/root/.local/share/ersatztv"
      - "{{ storage_path }}:/mnt/jbod:ro"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.ersatz.rule=Host(`ersatz.{{ m_wd_domain_me }}`)"
    ports:
      - 8409:8409
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped