services:
  # apps
  mealie:
    image: hkotel/mealie:v0.5.1
    container_name: mealie
    volumes:
      - "{{ appdata_path }}/apps/mealie:/app/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.mealie.rule=Host(`mealie.{{ wd_domain_me }}`)"
    environment:
      - DB_TYPE=sqlite
    restart: unless-stopped
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    volumes:
      - "{{ appdata_path }}/apps/freshrss:/config"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.freshrss.rule=Host(`rss.apps.wd.{{ domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  wallabag:
    image: wallabag/wallabag:latest
    container_name: wallabag
    volumes:
      - "{{ appdata_path }}/apps/wallabag:/var/www/wallabag/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.wallabag.rule=Host(`wallabag.apps.wd.{{ domain_me }}`)"
    environment:
      - "SYMFONY__ENV__DOMAIN_NAME=https://wallabag.apps.wd.{{ domain_me }}"
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_sqlite
    restart: unless-stopped
  stirlingpdf:
    image: frooodle/s-pdf:latest
    container_name: stirlingpdf
    volumes:
      - "{{ appdata_path }}/apps/stirlingpdf/configs:/configs"
      - "{{ appdata_path }}/apps/stirlingpdf/ocr-data:/usr/share/tesseract-ocr/5/tessdata"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.stirling.rule=Host(`pdf.apps.wd.{{ domain_me }}`)"
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:0.20.0
    container_name: hoarder-web
    labels:
      - traefik.enable=true
      - "traefik.http.routers.hoarder.rule=Host(`hoarder.apps.wd.{{ domain_me }}`)"
    volumes:
      - "{{ appdata_path }}/apps/hoarder/data:/data"
    ports:
      - 3030:3000
    environment:
      - MEILI_ADDR=http://hoarder-meilisearch:7700
      - "MEILI_MASTER_KEY={{ hoarder_nextauth_masterkey }}"
      - BROWSER_WEB_URL=http://hoarder-chrome:9222
      - NEXTAUTH_URL=http://localhost:3030
      - "NEXTAUTH_SECRET={{ hoarder_nextauth_secret }}"
      - DATA_DIR=/data
      # OPENAI_API_KEY: ...
      - "OLLAMA_BASE_URL=http://10.42.1.12:11434"
      - "INFERENCE_TEXT_MODEL=mistral"
      - "INFERENCE_IMAGE_MODEL=llama3.2"
    restart: unless-stopped
  hoarder-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: hoarder-chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped
  hoarder-meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: hoarder-meilisearch
    volumes:
      - "{{ appdata_path }}/apps/hoarder/meilisearch:/meili_data"
    environment:
      - "MEILI_NO_ANALYTICS=true"
      - NEXTAUTH_URL=http://hoarder-web:3030
      - "NEXTAUTH_SECRET={{ hoarder_nextauth_secret }}"
      - MEILI_ADDR=http://127.0.0.1:7700
      - "MEILI_MASTER_KEY={{ hoarder_nextauth_masterkey }}"
    restart: unless-stopped



