services:
  # monitoring
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    volumes:
      - "{{ appdata_path }}/smokeping/config:/config"
      - "{{ appdata_path }}/smokeping/data:/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.{{ wd_domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    hostname: morpheus
    restart: unless-stopped
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    labels:
      - traefik.enable=false
    ports:
      - 8008:80
    environment:
      - MODE=standalone
    restart: unless-stopped
  ## notifications
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    labels:
      - traefik.enable=true
      - "traefik.http.routers.ntfy.rule=Host(`notify.{{ wd_domain_me }}`)"
    volumes:
      - "{{ appdata_path }}/ntfy/lib:/var/lib/ntfy"
      - "{{ appdata_path }}/ntfy/cache:/var/cache/ntfy"
      - "{{ appdata_path }}/ntfy/etc:/etc/ntfy"
    environment:
      - "TZ={{ host_timezone }}"
      - "NTFY_BASE_URL=http://notify.{{ wd_domain_me }}"
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
    #user: "{{ docker_compose_generator_uid }}:{{ docker_compose_generator_gid }}"
    command:
      - serve
    restart: unless-stopped