services:
  dumbot:
    image: ghcr.io/shayne/dumbot:latest
    container_name: dumbot
    environment:
      - "TZ={{ host_timezone }}"
      - "ANTHROPIC_API_KEY={{ dumbot_anthropic_api_key }}"
      - "TELEGRAM_BOT_TOKEN={{ dumbot_telegram_bot_token }}"
      - "TAVILY_API_KEY={{ dumbot_tavily_api_key }}"
      - DUMBOT_DB_FILE=/data/dumbot.db
      - DUMBOT_STORAGE_DIR=/data
    volumes:
      - "{{ appdata_path }}/apps/dumbot:/data"
    restart: unless-stopped
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    container_name: immich-machine-learning
    ports:
      - 3003:3003
    volumes:
      - model-cache:/cache
    restart: unless-stopped
    environment:
      - MACHINE_LEARNING_PRELOAD__CLIP=ViT-SO400M-16-SigLIP2-384__webli
      - MACHINE_LEARNING_MODEL_TTL=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

volumes:
  model-cache:
