services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep
    volumes:
      - "{{ appdata_path }}/apps/karakeep/data:/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.karakeep.rule=Host(`keep.apps.{{ wd_domain_me }}`)"
    environment:
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - "NEXTAUTH_SECRET={{ hoarder_nextauth_secret }}"
      - "MEILI_MASTER_KEY={{ hoarder_nextauth_masterkey }}"
      - "NEXTAUTH_URL=https://keep.apps.wd.ktz.me"
      - "OPENAI_API_KEY={{ hoarder_openai_key }}"
      - DATA_DIR=/data
      - CRAWLER_STORE_SCREENSHOT=true
      - CRAWLER_FULL_PAGE_SCREENSHOT=true
      - CRAWLER_ENABLE_ADBLOCKER=true
      # auth
      - "OAUTH_WELLKNOWN_URL=https://id.wd.ktz.me/.well-known/openid-configuration"
      - "OAUTH_PROVIDER_NAME=pocketid"
      - "OAUTH_CLIENT_ID={{ karakeep_oauth_client_id }}"
      - "OAUTH_CLIENT_SECRET={{ karakeep_oauth_secret }}"
      #- "OAUTH_TIMEOUT=10000"
      - "OAUTH_SCOPE=openid email profile"
    restart: unless-stopped
  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    container_name: karakeep-chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - "MEILI_MASTER_KEY={{ hoarder_nextauth_masterkey }}"
    volumes:
      - "{{ appdata_path }}/apps/karakeep/meilisearch:/meili_data"
    restart: unless-stopped