services:
  # monitoring
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    volumes:
      - "{{ appdata_path }}/apps/smokeping/config:/config"
      - "{{ appdata_path }}/apps/smokeping/data:/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.{{ m_wd_domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    hostname: morpheus
    restart: unless-stopped
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    labels:
      - traefik.enable=false
    ports:
      - 8008:80
    environment:
      - MODE=standalone
    restart: unless-stopped
  # whatsupdocker:
  #   image: getwud/wud
  #   container_name: wud
  #   labels:
  #     - traefik.enable=true
  #     - "traefik.http.routers.wud.rule=Host(`wud.{{ m_wd_domain_me }}`)"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped